# Default 'global' options
ssl: false

#
# bigip_virtual_server
#
bigip_virtual_server:
  destination: "{{virtual_address}}"
  port: "{{port}}"
  all_rules: null
  default_persistence_profile: "source_addr"
  description: null
  name: "{{inventory_hostname}}_{{port}}"
  pool: "{{inventory_hostname}}_{{port}}"
  snat: "None"
  state: "enabled"
  partition: "{{partition}}"
  profiles:
    - "http"

#
# bigip_pool
#
bigip_pool:
  name: "{{inventory_hostname}}_{{port}}"
  monitors:
    - "http"
  monitor_type: "and_list"
  #lb_method: "round_robin"
  #quorum: null
  partition: "{{partition}}"

#
# bigip_node
#
bigip_node:
  name: "{{item.host}}"
  session_state: "enabled"
  node_state: "enabled"
  partition: "{{partition}}"

#
# bigip_pool_member
#
bigip_pool_member:
  name: "{{item.host}}"
  session_state: "enabled"
  state: "present"
  monitor_state: "enabled"
  port: "{{port}}"
  pool: "{{inventory_hostname}}_{{port}}"
  priority_group: 0
  partition: "{{partition}}"
  ratio: 1

#
# bigip_profile_client_ssl
#
bigip_profile_client_ssl:
  state: "present"
  name: "{{inventory_hostname}}_client_ssl"
  ciphers: "!SSLv3:!SSLv2:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA"
  parent: "/Common/clientssl"
  cert_key_chain:
    - cert: "{{inventory_hostname}}"
      key: "{{inventory_hostname}}"

#
# bigip_ssl_certificate
#
bigip_ssl_certificate:
  name: "{{inventory_hostname}}"
  state: "present"
  content: "{{certificate_cert}}"
  partition: "{{partition}}"

#
# bigip_ssl_key
#
bigip_ssl_key:
  name: "{{inventory_hostname}}"
  state: "present"
  content: "{{certificate_key}}"
  partition: "{{partition}}"
